# Generated by Django 5.1 on 2024-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField()),
                ('id_sucursal', models.CharField(max_length=11)),
                ('id_provedor', models.CharField(max_length=11)),
            ],
        ),
    ]
