# Generated by Django 5.1 on 2024-11-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=30)),
                ('hora', models.CharField(max_length=30)),
                ('id_producto', models.CharField(max_length=11)),
                ('id_cliente', models.CharField(max_length=11)),
                ('cantidad', models.PositiveIntegerField()),
                ('id_trabajador', models.CharField(max_length=11)),
                ('registro', models.CharField(max_length=45)),
            ],
        ),
    ]
