# Generated by Django 5.1 on 2024-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido_p', models.CharField(max_length=30)),
                ('apellido_m', models.CharField(max_length=30)),
                ('fecha_nac', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('celular', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
